# Generated by Django 5.0.6 on 2024-06-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='hashtags',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
